version: "3.5"

services:
  
  # GOLANG
  web:
    build: ./.docker/golang
    command: go run main.go
    volumes:
      - ./src/service-product:/var/www
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - db_mysql
    restart: unless-stopped
  
  # MYSQL
  db_mysql:
    build: ./.docker/mysql
    volumes: 
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox_service_product

networks:
  backend: